### ISSUE TITLE
use gstreamer

### ISSUE THREAD

**Issue by muuuh** [andyrblank/Commercial-Clapboard#1]
Hello,

not an issue, more an improval idea (you mentioned already in your blog).

perhaps you could use gstreamer in the chain for conversion to h264. For use of the gpu, you first have to give the GPU enough RAM through raspi-config or you will get a strange error message.

I found gstreamer pipelines difficult to handle. I tried to make a tvheadend post processing script with it.

Perhaps the new Rasberry Pi 2 will have enough resources.

```
#!/bin/sh
#https://tvheadend.org/projects/tvheadend/wiki/Tvheadend_post_recording_scripts
FULL_PATH=$1
PATH_WITHOUT_EXTENSION=$(echo "$FULL_PATH" | sed "s/....$//")

if [ "x$1" = "x" ]; then
    echo "wrong command line: convert.sh {full path to file}"
    exit
fi

#convert
#gst-launch-1.0 filesrc location="$FULL_PATH" ! decodebin name=demux demux. ! queue ! audioresample ! mux. matroskamux name=mux streamable=true ! filesink location="$PATH_WITHOUT_EXTENSION"_small.mp4 demux. ! queue ! progressreport update-freq=1 ! videoconvert ! omxh264enc target-bitrate=1344000 control-rate=variable ! "video/x-h264,profile=high" ! h264parse ! mux.

#downsample
#gst-launch-1.0 filesrc location="$FULL_PATH" ! decodebin name=demux demux. ! queue ! audioresample ! mux. matroskamux name=mux ! filesink location="$PATH_WITHOUT_EXTENSION"_small.mkv demux. ! queue ! progressreport update-freq=5 ! videoscale ! video/x-raw,width=480,height=320 ! deinterlace ! videoconvert ! omxh264enc target-bitrate=500000 control-rate=variable ! "video/x-h264,profile=high" ! h264parse ! mux.

gst-launch-1.0 filesrc location="$FULL_PATH" ! decodebin name=demux demux. ! queue ! audioresample ! mux. matroskamux name=mux ! filesink location="$PATH_WITHOUT_EXTENSION"_small.mkv demux. ! queue ! progressreport update-freq=5 ! videoscale ! video/x-raw,width=480,height=320 ! videoconvert ! omxh264enc target-bitrate=500000 control-rate=variable ! "video/x-h264,profile=high" ! h264parse ! mux.
```

**Comment by andyrblank** [comment]
@muuuh Thanks for the example pipes. I'll take a look and see if there's any options I can use that I'm not aware of yet and "difficult to handle" is an understatement. I've been trying to tackle them and I'm making headway with a few issues still left in the output. Here's where I'm at so far:

gst-launch-1.0 filesrc location="$WorkPath"/"$FileName" \
        ! queue \
        ! tsdemux name=demuxer mp4mux name=mux \
        ! queue \
        ! filesink location="$WorkPath"/"$OutputName" demuxer.\
        ! mpegvideoparse \
        ! queue \
        ! omxmpeg2videodec \
        ! videoconvert \
        ! omxh264enc \
        ! "video/x-h264,control-rate=1,target-bitrate=3000" \
        ! h264parse \
        ! mux.  demuxer. \
        ! queue \
        ! avdec_ac3 \
        ! audioconvert \
        ! lamemp3enc \
        ! mux.

**Comment by andyrblank** [comment]
Also what I like about the way I'm trying to tackle it is I get to use omxmpeg2videodec specifically so that I know the MPEG2 decoding is not happening in software (and I paid for the MPEG2 license so I want to use it). I'm having trouble linking this to the avenc_ac3 though for the audio. The best would be if I could find out how to write the pipe to copy the audio without decoding->encoding.
